# Generated by Django 5.2.17 on 2026-09-28 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_alter_course_options"),
        ("flashcards", "0002_flashcard_is_edited"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("cards_reviewed", models.PositiveIntegerField(default=0)),
                ("cards_correct", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("was_correct", models.BooleanField()),
                ("box_before", models.PositiveSmallIntegerField()),
                ("box_after", models.PositiveSmallIntegerField()),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="flashcards.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="study.studysession",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["course", "started_at"], name="study_study_course__925ad0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studysession",
            constraint=models.CheckConstraint(
                condition=models.Q(("cards_correct__lte", models.F("cards_reviewed"))),
                name="session_correct_within_reviewed",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewlog",
            index=models.Index(
                fields=["flashcard", "reviewed_at"],
                name="study_revie_flashca_e41a2a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewlog",
            index=models.Index(
                fields=["user", "reviewed_at"], name="study_revie_user_id_9971e9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewlog",
            constraint=models.CheckConstraint(
                condition=models.Q(("box_before__gte", 1), ("box_before__lte", 5)),
                name="review_box_before_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewlog",
            constraint=models.CheckConstraint(
                condition=models.Q(("box_after__gte", 1), ("box_after__lte", 5)),
                name="review_box_after_in_range",
            ),
        ),
    ]
