# Generated by Django 5.2.17 on 2026-09-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="mode",
            field=models.CharField(
                choices=[("due", "Due cards"), ("practice", "Extra practice")],
                default="due",
                max_length=10,
            ),
        ),
    ]
