# Generated by Django 5.2.17 on 2026-09-27 14:41

import django.db.models.deletion
import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_alter_course_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("text", "Pasted text"), ("pdf", "PDF")], max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to=materials.models.material_upload_to
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("raw_text", models.TextField(blank=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["course", "-created_at"],
                        name="materials_m_course__143253_idx",
                    )
                ],
            },
        ),
    ]
