# Generated by Django 5.2.17 on 2026-09-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="generation_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Queued"),
                    ("processing", "Reading text"),
                    ("generating", "Generating cards"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
