# Generated by Django 5.2.17 on 2026-09-27 14:37

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": [django.db.models.functions.text.Lower("name")]},
        ),
    ]
