# Generated by Django 5.2.17 on 2026-09-27 14:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_alter_course_options"),
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "concept_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="concept"
                    ),
                ),
                ("source_excerpt", models.TextField(blank=True)),
                (
                    "box",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "next_review_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="courses.course",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flashcards",
                        to="materials.material",
                    ),
                ),
            ],
            options={
                "ordering": ["concept_label", "created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["course", "next_review_at"],
                        name="flashcards__course__e92564_idx",
                    ),
                    models.Index(
                        fields=["course", "box"], name="flashcards__course__b3c0b3_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("box__gte", 1), ("box__lte", 5)),
                        name="flashcard_box_in_range",
                    )
                ],
            },
        ),
    ]
