# Generated by Django 5.2.17 on 2026-09-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]
